### DISCUSSION TITLE
In Docker Session works only in same Controller Only

### DISCUSSION THREAD

**Discussion by mahen3d** [phalcon/cphalcon#15291] [Q&A]
I am using phalcon 3.4.5 and php7.3, i have noticed that Session is only working in the same action, when you redirect to a new controller you will see all the session vars get empty. Any idea on how to fix this issue?

docker file 
```
nginx:
  image: nginx:latest
  ports:
     - "80:80"
#    - "443:443"
  volumes:
    - ./:/var/www/vhosts/ss/httpdocs
    - ./.config/etc/nginx/:/etc/nginx/
    - ./.config/var/logs/nginx/:/var/logs/
  links:
    - php
redis:
  image: redis:latest
  ports:
    - "6379:6379"
  command: [ "redis-server", "/redis.conf" ]
  volumes:
    - ./.config/redis/redis.conf:/redis.conf
  restart: always
  environment:
    - REDIS_REPLICATION_MODE=master
```

And the session init is like 

```
 $di->set('session' , function () use ($config) {
            $session = new \Phalcon\Session\Adapter\Redis(
                [
                    "uniqueId"   => $config->site->redis_uid,
                    "host"       =>  $config->site->redis_host,
                    "port"       =>  $config->site->redis_port,
                    //"auth"       => $config->site->redis_pass,
                    "persistent" => true,
                    "lifetime"   => 3600,
                    "prefix"     => $config->site->redis_uid."_",
                    "index"      => 1,
                ]
            );
            $session->start();
            return $session;
        });
```

In index controller, you set it as 

```
 $this->session->set("sss", true);
//then redirect
                // A HTTP Redirect
                $this->flash->clear();
                $this->response->redirect('/home');
```

In the home controller, you see
```
 if ($this->session->has('sss') === false) is empty`
```

**Only happens in the Docker enr. Live is fine.**
