### DISCUSSION TITLE
Yet Another Convoluted Documentation

### DISCUSSION THREAD

**Discussion by gander** [phalcon/cphalcon#16772] [General]
Is it so hard to understand that a person would like to go into the documentation, and being guided by the hand, in 5 minutes start his application instance? Version with `php -S` and `docker compose`. Would it hurt you so much to do it? It is extremely impudent to say that a given solution is easy and fast to implement, when the documentation causes physical pain when trying to start. I say this as a PHP programmer with 20 years of experience: your documentation sucks.

---

No ignoring the topic in the style of "since you succeeded, it's not a problem anymore?" I demand: put it on the first page of your documentation, and you will do the greatest benefit to future users:

```bash
composer global require phalcon/devtools:"^5.0@dev" --dev
```

```bash
phalcon create-project phalcon-playground
```

```yaml
services:
    phalcon:
        image: phalconphp/cphalcon:v5.9.3-php8.4
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        command: ["php", "-S", "0.0.0.0:80", "-t", "public/", ".htrouter.php"]
```
