### ISSUE TITLE
[NFR] Env Yaml filter/function

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#13189]
Our Yaml Config Adapter should recognize `env`  filter/function to call `$_ENV`/`getenv`. Example:

```yaml
database:
    adapter: Mysql
    host: '%env(DB_HOST)%'
    username: root
    password: secret
    dbname: vokuro
logger:
    logLevel: '%env(APP_ENV)%'
    # ...
```
