### ISSUE TITLE
[NFR]: Enable `jpeg` support in GD in CI (when ready)

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/cphalcon#15420]
Some of our tests require `jpeg` support and currently it is not possible to install PHP inside Ubuntu with this option.

Wait until next version of `shivammathur/setup-php` action to integrate this feature inside our CI.

Potential syntax to achieve that (https://github.com/shivammathur/test-setup-php/actions/runs/768848306/workflow):
```
env:
          GD_CONFIGURE_OPTS: --enable-gd=shared,/usr --with-external-gd --with-jpeg
          GD_LIBS: libgd-dev libjpeg-dev
          GD_PATH: ext/gd
```

Refs:
* https://github.com/shivammathur/setup-php/discussions/445
* https://github.com/shivammathur/setup-php/discussions/418
